---
name: Transportauftrag
about: Transportauftrag für Anpassungen
title: Transport Dokumente für [release, change] in Umgebung [umgebung]
labels: ''
assignees: ''
projects: "projects/2"
body:
- type: dropdown
  id: release
  label: Welche Art von Release
  options:
    - Minor Corporate
    - Major Corporate
    - Minor Release
  validations:
    required: true
---


